baseURL = "https://ramzaveri.netlify.app/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
publishDir = "docs"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
 

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "index.html#about"
  weight = 2

  [[menu.header]]
  name = "Experience"
  URL = "index.html#experience"
  weight = 3

  [[menu.header]]
  name = "Publications"
  URL = "index.html#publication"
  weight = 4

  [[menu.header]]
  name = "Awards"
  URL = "index.html#awards"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "index.html#contact"
  weight = 6


  [[menu.footer]]
  name = "About"
  URL = "index.html#about"
  weight = 2


  [[menu.footer]]
  name = "Books"
  URL = "/books"
  weight = 3

  [[menu.footer]]
  name = "Public Speaking"
  URL = "/public-speaking"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "index.html#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "publication", "awards", "contact"]
  googleTagManagerID = "GTM-NVN2BJG" # Google Analytics works with Google Tag Manager
  homepageExperienceCount = 3

  [params.logo]
    text1 = "Ram"
    text2 = "Zaveri"

  [params.footer]
